main.go
pgmgr/pgmgr.go

This change should make it easier to use pgmgr alongside other Postgres tools, as it will use the standard `PGHOST`, `PGUSERNAME`, `PGPASSWORD`, `PGPORT`, and `PGDATABASE` variables to configure itself if other configuration is absent.
Fixes #3.

Support standard Postgres environment variables

---

main.go
pgmgr/config.go
pgmgr/config_test.go
pgmgr/pgmgr.go
pgmgr/pgmgr_test.go

Having all of the configuration loading in main.go makes it hard to test. This moves it into the `pgmgr` package, which will make it easier to add tests for.

Config refactor

---

README.md
main.go
pgmgr/config.go
pgmgr/config_test.go
pgmgr/pgmgr.go
pgmgr/pgmgr_test.go

I have a project moving from ActiveRecord to go, so it'd be nice if pgmgr could support schema migrations in the same format. Plus epoch time is annoying. =)
I haven't tested this branch out on that project yet; there's probably more to be done still. Just getting the PR in now.

Support Rails-style version format and column type

---

README.md
main.go
pgmgr/config.go
pgmgr/config_test.go
pgmgr/pgmgr.go
pgmgr/pgmgr_test.go

This currently includes all of #12; I'll rebase after I get that PR working reasonably.
I don't want `schema_migrations` in my public schema. This exposes Yet Another Config Option :tm: to control the table name, optionally schema qualified. If the schema does not exist, pgmgr will create it, and then create the table inside of it.

Configurable schema_migrations table name and schema

---

pgmgr/config_test.go
pgmgr/pgmgr_test.go

Extracts a few helpers for code I kept copying into each new test.
I also removed the references to `pgmgr.` from within the test files, as they are also in the pgmgr package. This leads to weird situations such as this type error, because the imported `pgmgr` is a different package from the "current" package or whatever the correct name is:
~~~go
var x *pgmgr.Config
x := &Config{}
~~~
See the commit message 9e98ca4. If my next PR didn't include a sanity check test on a private function, I could've taken that route instead.

Tidy up tests

---

pgmgr/pgmgr.go
pgmgr/pgmgr_test.go

My previous change in #13 introduced the bug that, if the
schema_migrations table exists but was empty, the Initialize function
would be called and then fail attempting to create the table.
Instead, I've pulled the check for the table's existence into Initialize
itself, so that it can simply opt-out of creating it.

Ensure Initialize can run multiple times

---

pgmgr/pgmgr.go
pgmgr/pgmgr_test.go

I had an issue with running migrations while one of the migration files is being edited by vim. It creates a .swp file which ends up being recognized as a migration. As a result, I made the filename regular expression stricter.

Make the filename regular expression stricter

---

README.md
pgmgr/pgmgr.go
pgmgr/pgmgr_test.go

* Add tests for the `Rollback()` function
* Print out the error message on a failed `Rollback()`. I had an issue where it only said applying the `down` migration without telling me if it finished or not. To debug I always had to run the .sql file via `psql`.
* Added the `rollback` explanation to the README
One more thing to consider is that I changed the failure errors in `Migrate` to print to stderr instead of stdout. I hope this won't cause any issues. If it is an issue, I can change the `fmt.Fprintf`'s to print to stdout.

Print out error message on failed rollback

---

pgmgr/pgmgr.go

Apparently there is a missing newline since I changed it to use `fmt.Fprintf`. It kind of messes up the formatting.

Add a missing newline in the error message

---

.travis.yml

This appears to have been added recently as a restriction for golint, which is why previous builds worked.  Eventually we'll probably be able to just not run CI on 1.4, but for now we'll just exclude golint for those builds.

Only run golint for Go 1.5+

---

main.go

When the command `pgmgr migration ...` fails, the error message never made it to the console.

Now displays error message on failure to create a migration

---

README.md
main.go
pgmgr/config.go
pgmgr/config_test.go
pgmgr/pgmgr.go
pgmgr/pgmgr_test.go

For supported values of this parameter and their meanings, see [the docs](https://www.postgresql.org/docs/9.1/static/libpq-ssl.html). Can be configured in pgmgr by either the `--sslmode` CLI flag, the `"sslmode"` attribute in `.pgmgr.json`, the `PGMGR_SSLMODE` env var, or the default `PGSSLMODE` envvar.
Closes #26.

Add support for Postgres' sslmode connection parameter

---

pgmgr/config.go
pgmgr/config_test.go

As described in https://github.com/go-bootstrap/go-bootstrap/issues/47, a database name of `test.db` (which contains a period) when supplied in a connection URL (`PGMGR_URL=postgresql://localhost:5432/test.db`) is not parsed correctly. This PR fixes the issue by  changing the regex to just match anything that's not the query separator (`?`).

Loosen URL-matching regex to handle all database names.

---

.travis.yml

Now that Go has released 1.7, I want to make sure pgmgr maintains compatibility with 1.6. Possibly we could remove 1.4, but it's not that old and I can't find a good source on version usage.

Test on Go v1.6 in CI

---

pgmgr/pgmgr.go

Not entirely sure what exposed this behavior -- possibly a Travis change, or a Postgres version change, or a pq change -- but the change here makes sense regardless. `dbname` should likely always be present, but we'll leave it up to the adapter to decide that.

[fix] Build the connection string with only known values

---

.travis.yml
README.md
TODO.md
main.go
pgmgr/config.go
pgmgr/pgmgr.go
pgmgr/pgmgr_test.go

1) This introduces a new MigrationDriver config variable, which can be either "pq" (the current method) or "psql" (a new method that invokes psql directly). For now that variable will remain defaulted to "pq" until we've proven out the psql driver at Enova.
The main benefit of the psql driver is that your migrations are executed one statement at a time, rather than as a multi-command statement. This enables things like multiple concurrent index creation and works better with logical replication.
2) Certain commands like "db create" and "db dump" did not use the configured connection variables, instead using whatever your environment's PG vars were set to. This wasn't a huge deal as those commands weren't used in prod, but it still was a frequent cause of confusion. The fix was to dump …

PSQL migration driver & create/drop/dump fixes

---

.travis.yml

pgmgr's dependencies don't resolve for go 1.10 currently; since that's now several versions behind I'm going to drop it off of the travis builds.

Drop go 1.10 support

---

pgmgr/pgmgr.go
pgmgr/pgmgr_test.go

1. Migrations may not always have semicolons at the end -- that's OK per normal psql behavior, so we should allow it for the psql driver. We accomplish this just by pre-pending a semicolon to the version increment statement, which is always safe to do.
2. Some users have duped the SQLConnectionString logic into their own apps, when trying to share pgmgr's config values for their own db connections, so we now export that function.

Psql Migrations: follow-up

---

main.go

This is so that running `pgmgr --version` will output 1.0.0 in the corresponding branch

bump version string to 1.0.0

---

.travis.yml
go.mod
go.sum
main.go

The CLI package has stabilized its master branch to be locked at v1, so the gopkg.in hack is no longer needed (and was breaking module resolution when trying to install pgmgr).

Drop gopkg.in for module compatibility

---

pgmgr/pgmgr.go
pgmgr/pgmgr_test.go

This was a missing part of the psql driver that broke rollback migrations as the schema version was attempted to be re-inserted during the rollback.

Add omitted rollback support for psql driver

---

main.go
pgmgr/dump_config.go
pgmgr/dump_config_test.go
pgmgr/pgmgr.go
pgmgr/pgmgr_test.go

🍏 📗 💚 
By default we always compress. There was an issue with negation with the `compress` flag so it had to be changed to `no-compress`.
There was also an issue with the `gz` file being read when compressed, so that has been updated to write to a brand new file that gets removed.

Change compress to no-compress & update how gz file is read

---

main.go
pgmgr/pgmgr.go

🍏 📗 💚 
Failing to load with `exit 1` when a dump file doesn't exist is harsh (for scripting purposes). It's more useful to fail when something actually goes wrong with loading the dump.

Gracefully exit db load when dump file is missing

---

pgmgr/config.go
pgmgr/config_test.go

Use `column-type` either passed from argument or through environment variables instead of default value if no config file is provided.

Use column-type from context if provided

---

main.go
pgmgr/config.go

Drop defaults from the CLI layer, as they always took precedence over values from the config file. That is, setting column-type: string in your JSON would no longer work, as the default value of "integer" from the CLI would always override it. This also fixes the CLI values to be applied for column format and migration table, where previously they were ignored.

Fix erroneous defaults

---

pgmgr/pgmgr.go
pgmgr/pgmgr_test.go

A migration that ended in a comment, like:
```sql
CREATE TABLE foos (bar INTEGER);
-- okay, done
```
Would append its version-incrementing statement like so:
```sql
CREATE TABLE foos (bar INTEGER);
-- okay, done; INSERT INTO schema_migrations (version) VALUES (...);
```
Causing the version not to increment. To fix this, I'm appending a newline before the INSERT.

Fix psql driver bug with comment-ending migrations
